- name: Create virtual environment
  become: true
  command: 
    cmd: python3.10 -m venv /home/clouduser/elucidate-capstone/project-env
    creates: /home/clouduser/elucidate-capstone/project-env

- name: Install requirements
  become: true
  pip: 
    requirements: /home/clouduser/elucidate-capstone/S24-BDA/requirements.txt
    virtualenv: /home/clouduser/elucidate-capstone/project-env
    virtualenv_python: python3.10