- name: Add apt key
  become: true
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys F23C5A6CF475977595C89F51BA6932366A755776

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Python 3.10 and venv
  ansible.builtin.apt:
    name:
      - python3.10
      - python3.10-venv
      - python3-pip
    state: present
