---
- hosts: all
  become: true
  vars_prompt:
    - name: "username"
      prompt: "Enter your github username"
      private: false
    - name: "user_pat"
      prompt: "Enter your github PAT"
      private: true
  
  roles:
    - role: get-repo
      vars:
        github_user: "{{ username }}"
        github_PAT: "{{ user_pat }}"
    - install-python
    - setup-python-environment
    - major-packages
