- name: create destination directory
  # This task creates the destination directory for the files.
  ansible.builtin.file:
    path: /home/clouduser/cloud-native/
    state: directory
    recurse: true

- name: Clone GitHub repository
  ansible.builtin.git:
    repo: 'https://{{ username }}:{{ user_pat }}@github.com/AI-Technicians-Capstone-Projects/S24-BDA.git'
    dest: /home/clouduser/cloud-native/project-3