- name: Create temp directory
  # This task creates the destination directory for the handout.
  ansible.builtin.file:
    path: /tmp/handout
    state: directory

- name: create destination directory
  # This task creates the destination directory for the handout.
  ansible.builtin.file:
    path: /home/clouduser/multi-model-databases
    state: directory

- name: Download Handout
  # This will be the task for getting handouts. Change links as necessary.
  # The links here are from week 5 of the Data Engineer course. They are
  # just placeholders.
  get_url:
    url: "https://clouddataengineer.blob.core.windows.net/multi-model-databases/handout/multi-model-databases.gz"
    dest: /tmp/handout/multi-model-databases.gz
  register: handout
  ignore_errors: true

- name: Check if handouts file exists
  # This task checks if the handouts file exists. If it does, the task will be skipped.
  ansible.builtin.stat:
    path: /tmp/handout/multi-model-databases.gz
  register: handouts_file

- name: Unzip Handouts
  # This task will unzip the handout and print the upacked files to the console.
  unarchive:
    src: /tmp/handout/multi-model-databases.gz
    dest: /home/clouduser/
    remote_src: yes
  register: unzip_result
  when: handouts_file.stat.exists

- name: Get Additional Resources
  # This task is optional. If there are no additiional resources, you can comment it out or delete it.
  get_url:
    url: "https://clouddataengineer.blob.core.windows.net/f19-data-engineer/datasets/multi-model-databases/movieReview.json"
    dest: /home/clouduser/multi-model-databases

- name: List contents of multi-model-databases
  become: true
  command: ls -l /home/clouduser/multi-model-databases
  register: ls_output

- name: Show ls_output
  debug:
    var: ls_output.stdout_lines

- name: Remove tmp directory
  # This will remove the tmp directory after the handout has been unzipped.
  ansible.builtin.file:
    path: /tmp/handout/
    state: absent