- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.asc

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update and ungrade apt cache
  apt:
    update_cache: true
    upgrade: dist

- name: Install required packages
  apt:
    name:
      - maven
      - openjdk-17-jdk
      - openjdk-17-jre
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - azure-cli
      - jq
      - git
      - make
      - python3-pip
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Install Kubectl
  ansible.builtin.snap:
    name: kubectl
    classic: true
    state: present

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Run Helm install script
  ansible.builtin.shell: "/tmp/get_helm.sh"

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes